steps:
  - name: 'ubuntu'
    args: ['cat', 'cloudbuild.yaml']
    id: 'debug-cloudbuild-yaml'
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/aiteach-backend:staging', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aiteach-backend:staging']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'aiteach-backend-staging'
    - '--image'
    - 'gcr.io/$PROJECT_ID/aiteach-backend:staging'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8000'
    - '--memory'
    - '512Mi'
    - '--cpu'
    - '1'
    - '--max-instances'
    - '10'
    - '--concurrency'
    - '80'
    - '--timeout'
    - '300'
    - '--set-env-vars'
    - 'DEBUG=False,LOG_LEVEL=INFO,GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
    - '--update-secrets'
    - 'DATABASE_URL=database-url:latest,JWT_SECRET_KEY=jwt-secret-key:latest'
    - '--add-cloudsql-instances'
    - '$PROJECT_ID:us-central1:aiteach-db'
    secretEnv: ['DATABASE_URL', 'JWT_SECRET_KEY']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/database-url/versions/latest
    env: 'DATABASE_URL'
  - versionName: projects/$PROJECT_ID/secrets/jwt-secret-key/versions/latest
    env: 'JWT_SECRET_KEY'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

images:
  - gcr.io/$PROJECT_ID/aiteach-backend:staging